# Generated by Django 5.1.2 on 2024-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
