# Generated by Django 5.1.1 on 2024-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('BERAT', 'Makanan Berat dan Nasi'), ('OLAHAN', 'Olahan Ayam dan Daging'), ('MIE', 'Mie, Pasta, dan Spaghetti'), ('SNACK', 'Makanan Ringan dan Cemilan')], default='FOOD', max_length=10),
        ),
    ]
