# Generated by Django 5.1.1 on 2024-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Makanan Berat dan Nasi', 'Makanan Berat dan Nasi'), ('Olahan Ayam dan Daging', 'Olahan Ayam dan Daging'), ('Mie, Pasta, dan Spaghetti', 'Mie, Pasta, dan Spaghetti'), ('Makanan Ringan dan Cemilan', 'Makanan Ringan dan Cemilan')], default='Makanan Berat dan Nasi', max_length=50),
        ),
    ]
